import type { Metadata } from "next";
import Sidebar from "@/components/common/sidebar";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ProtectedLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Sidebar>
            {children}
        </Sidebar>
    );
}
